# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .

dependencies:
  - sphinx==4.4.0
  - sphinx_rtd_theme==1.0.0
  - sphinxcontrib-apidoc==0.3.0